title: Vladimir Danilov — web-developer
email: danilov@vlinc.ru

github: [metadata]
remote_theme: dan1lov/jekyll-danilov-blog

plugins:
  - jekyll-remote-theme

include:
  - _pages

header_pages:
  - index.md
  - _pages/projects.md
  - _pages/blog.md
